version: "3.4"
services:
  pigpio:
    image: francoisgervais/pigpio:v71
    ports:
      - 8888:8888
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/mem
      - /dev/vcio
  fan-control:
    build:
      context: .
    image: fan-control
    environment:
      - PYTHONUNBUFFERED=1
      - GPIOZERO_PIN_FACTORY=pigpio
      - PIGPIO_ADDR=pigpio
    volumes:
       - /sys/class/thermal/thermal_zone0/temp:/sys/class/thermal/thermal_zone0/temp
    depends_on:
      - pigpio
